# Generated by Django 3.1 on 2021-11-19 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='모임 제목', max_length=30)),
                ('content', models.CharField(help_text='모임 내용', max_length=200)),
                ('url', models.URLField()),
                ('grade', models.IntegerField(blank=True, choices=[(1, '아이언'), (2, '브론즈'), (3, '실버'), (4, '골드'), (5, '플래티넘'), (6, '다이아'), (7, '마스터'), (8, '그랜드마스터'), (9, '챌린저')], null=True)),
                ('age_range', models.IntegerField(blank=True, choices=[(1, '10대'), (2, '20대'), (3, '30대'), (4, '40대'), (5, '50대')], null=True)),
                ('cheer', models.IntegerField(blank=True, choices=[(1, 'DWF_KIA'), (2, 'T1'), (3, 'Gen_G'), (4, 'NongShim_REDFORCE'), (5, 'Liiv_SANDBOX'), (6, 'Afreeca Freecs'), (7, 'kt Rolster'), (8, 'Hanwha_Life_Esports'), (9, 'Fredit_BRION'), (10, 'DRX')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
