# Generated by Django 3.1 on 2021-11-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedmember',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
