# Generated by Django 3.1 on 2021-11-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20211119_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
